import { Router } from "express";
import { accountsRouter } from "../modules/accounts/accounts.routes.js";
import { authRouter } from "../modules/auth/auth.routes.js";
import { healthRouter } from "../modules/health/health.routes.js";
import { incomeSourcesRouter } from "../modules/income-sources/income-sources.routes.js";
import { incomeRouter } from "../modules/income/income.routes.js";
import { categoriesRouter, subcategoriesRouter } from "../modules/categories/categories.routes.js";
import { transactionsRouter } from "../modules/transactions/transactions.routes.js";
import { budgetTemplatesRouter } from "../modules/budgets/budget-templates.routes.js";
import { budgetsRouter } from "../modules/budgets/budgets.routes.js";
import { fixedExpensesRouter } from "../modules/fixed-expenses/fixed-expenses.routes.js";
import { recurringTransactionsRouter } from "../modules/recurring-transactions/recurring-transactions.routes.js";
import { savingsRouter } from "../modules/savings/savings.routes.js";
import { investmentsRouter } from "../modules/investments/investments.routes.js";
import { loansRouter } from "../modules/loans/loans.routes.js";
import { financialGoalsRouter } from "../modules/financial-goals/financial-goals.routes.js";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes.js";
import { reportsRouter } from "../modules/reports/reports.routes.js";
import { analyticsRouter } from "../modules/analytics/analytics.routes.js";
import { exportsRouter } from "../modules/exports/exports.routes.js";
import { netWorthRouter } from "../modules/net-worth/net-worth.routes.js";
import { notificationsRouter } from "../modules/notifications/notifications.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/accounts", accountsRouter);
apiRouter.use("/income-sources", incomeSourcesRouter);
apiRouter.use("/income", incomeRouter);
apiRouter.use("/categories", categoriesRouter);
apiRouter.use("/subcategories", subcategoriesRouter);
apiRouter.use("/transactions", transactionsRouter);
apiRouter.use("/budget-templates", budgetTemplatesRouter);
apiRouter.use("/budgets", budgetsRouter);
apiRouter.use("/fixed-expenses", fixedExpensesRouter);
apiRouter.use("/recurring-transactions", recurringTransactionsRouter);
apiRouter.use("/savings-goals", savingsRouter);
apiRouter.use("/investments", investmentsRouter);
apiRouter.use("/loans", loansRouter);
apiRouter.use("/financial-goals", financialGoalsRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/analytics", analyticsRouter);
apiRouter.use("/exports", exportsRouter);
apiRouter.use("/net-worth", netWorthRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/health", healthRouter);
